# Generated by Django 3.0.7 on 2020-07-18 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasolinera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre (obligatorio)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección (opcional)')),
            ],
            options={
                'verbose_name': 'Gasolinera',
                'verbose_name_plural': 'Gasolineras',
            },
        ),
        migrations.CreateModel(
            name='Lavadero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre (obligatorio)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección (opcional)')),
                ('correo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo (opcional)')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono (opcional)')),
            ],
            options={
                'verbose_name': 'Lavadero',
                'verbose_name_plural': 'Lavaderos',
            },
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Nombre de la marca')),
            ],
            options={
                'verbose_name': 'Marca del Vehiculo',
                'verbose_name_plural': 'Marcas de los Vehiculos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre (obligatorio)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección (opcional)')),
                ('correo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo (opcional)')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono (opcional)')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
            },
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Combustible',
                'verbose_name_plural': 'Tipos de Combustibles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoLavado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre (obligatorio)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
            ],
            options={
                'verbose_name': 'Tipo de lavado',
                'verbose_name_plural': 'Tipos de lavados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre (obligatorio)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
            ],
            options={
                'verbose_name': 'Tipo Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de vehículo')),
            ],
            options={
                'verbose_name': 'Tipo de Vehiculo',
                'verbose_name_plural': 'Tipos de Vehiculos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del vehículo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=15, unique=True, verbose_name='Placa')),
                ('anio', models.CharField(max_length=4, verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=40, null=True, verbose_name='Color')),
                ('tanque', models.IntegerField(verbose_name='Capacidad Tanque')),
                ('num_chasis', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numero del Chasis')),
                ('VIN', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='VIN')),
                ('matricula', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='Matrícula')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/%Y/%m/%d', verbose_name='Imagen del vehiculo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.MarcaVehiculo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoVehiculo')),
                ('usuario', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='RecargaCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_galon', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio del galón')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Costo del servicio')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='recibos_recargas/%Y/%m/%d')),
                ('kilometraje', models.IntegerField(verbose_name='Kilometraje')),
                ('nota', models.TextField(blank=True, null=True)),
                ('gasolinera', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Gasolinera')),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoCombustible')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Vehiculo')),
            ],
            options={
                'verbose_name': 'Recarga de Combustible',
                'verbose_name_plural': 'Recargas de Combustibles',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de servicio')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor')),
                ('nota', models.TextField(blank=True, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='recibos_matenimientos/%Y/%m/%d')),
                ('razon', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], default='Correctivo', max_length=11)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Taller')),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoMantenimiento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Vehiculo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Lavado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de servicio')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor')),
                ('nota', models.TextField(blank=True, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='recibos_lavados/%Y/%m/%d')),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Lavadero')),
                ('tipo_lavado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoLavado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Vehiculo')),
            ],
            options={
                'verbose_name': 'Lavado',
                'verbose_name_plural': 'Lavados',
                'ordering': ['fecha'],
            },
        ),
    ]
