# Generated by Django 3.0.7 on 2020-06-06 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='usuario',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dueño'),
        ),
        migrations.AddField(
            model_name='recargacombustible',
            name='gasolinera',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Gasolinera'),
        ),
        migrations.AddField(
            model_name='recargacombustible',
            name='tipo_combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoCombustible'),
        ),
        migrations.AddField(
            model_name='recargacombustible',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Vehiculo'),
        ),
        migrations.AddField(
            model_name='odometro',
            name='vehiculo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Vehiculo'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Local'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoMantenimiento'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Vehiculo'),
        ),
        migrations.AddField(
            model_name='lavado',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Local'),
        ),
        migrations.AddField(
            model_name='lavado',
            name='tipo_lavado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoLavado'),
        ),
        migrations.AddField(
            model_name='lavado',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Vehiculo'),
        ),
        migrations.AlterUniqueTogether(
            name='odometro',
            unique_together={('vehiculo', 'distancia')},
        ),
    ]
