# Generated by Django 3.0.7 on 2020-07-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_marcavehiculo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcavehiculo',
            name='imagen',
        ),
    ]
