# Generated by Django 3.0.7 on 2020-07-03 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20200608_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavado',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de servicio'),
        ),
        migrations.AlterField(
            model_name='lavado',
            name='local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Local'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de servicio'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Local'),
        ),
        migrations.AlterField(
            model_name='recargacombustible',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Costo del servicio'),
        ),
    ]
