# Generated by Django 3.0.7 on 2020-08-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20200808_1735'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tipovehiculo',
            constraint=models.UniqueConstraint(fields=('nombre', 'usuario'), name='tipo_vehiculo_por_usuario'),
        ),
    ]
